name: clusters
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - astropy
  - astroquery
  - jupyterlab
  - matplotlib
  - numba
  - numpy
  - pandas
  - requests
  - scikit-learn
  - scipy
